service: serverless-banking

frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  isLocal: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    IS_LOCAL: ${self:custom.isLocal}

functions:
# User
  userCreate:
    handler: src/app/userHandler.create
    events:
      - http:
          path: /register
          method: post
  userLogin:
    handler: src/app/userHandler.login
    events:
      - http:
          path: /login
          method: post
# Customer
  customerCreate:
    handler: src/app/customerHandler.create
    events:
      - http:
          path: /customer
          method: post
  customerGet:
    handler: src/app/customerHandler.get
    events:
      - http:
          path: /customer/{id}
          method: get         
# Account
  accountCreate:
    handler: src/app/accountHandler.create
    events:
      - http:
          path: /account
          method: post

  accountGetBalance:
    handler: src/app/accountHandler.getBalance
    events:
      - http:
          path: /account/{id}/balance
          method: get

  accountLock:
    handler: src/app/accountHandler.lock
    events:
      - http:
          path: /account/{id}/lock
          method: post
          
  accountUnlock:
    handler: src/app/accountHandler.unlock
    events:
      - http:
          path: /account/{id}/unlock
          method: post 
# Payment
  paymentCreate:
    handler: src/app/paymentHandler.create
    events:
      - http:
          path: /payment
          method: post 